my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_list.insert(1,'привет')
print(my_list)
removed = my_list.pop(3)
print(my_list)
print(removed)
print(my_list[1:5])
my_list.reverse()
print(my_list)
my_list_rev = list(reversed(my_list))
